#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 500
#define QUICK_TAP_TERM 0
//#define HOLD_ON_OTHER_KEY_PRESS
#define PERMISSIVE_HOLD
#define RGBLIGHT_SLEEP
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
